name: Tests unitaire Python
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
        pip install pygame
        pip install numpy

    - name: Run tests and generate HTML report
      run: |
        python testUnitaires.py
      env:
        CI: true
